# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [74]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [75]:
A = np.arange(1, 16).reshape(3,5)

In [76]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

2
(3, 5)
15
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [77]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [78]:
print(B-C)
print()
print(B*C)
print()
print(B@C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [79]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [80]:
print('Exponentiate each number elementwise:', np.exp(B[:]))
print()

print('Minimum value in the whole matrix:', np.min(B))
print()

print('Minimum value in each row:', B.min(axis = 1))
print()

print('Minimum value of each column:', B.min(axis = 0))
print()

print('Index value of the minimum value in the whole matrix:', np.argmin(B))
print()

print('Index value of the minimum value in each row:', B.argmin(axis = 1))
print()

print('Sum of all elements:', np.sum(B))
print()

print('Mean for each column:', B.mean(axis = 0) )
print()

print('Median for each column:', np.median(B, axis = 0))

Exponentiate each number elementwise: [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in the whole matrix: 1

Minimum value in each row: [1 4 7]

Minimum value of each column: [1 2 3]

Index value of the minimum value in the whole matrix: 0

Index value of the minimum value in each row: [0 0 0]

Sum of all elements: 45

Mean for each column: [4. 5. 6.]

Median for each column: [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [81]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [82]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

When you provide fewer indices than axes, it will index the leftmost index.

In the case of A, it has two dimensions. 

Therefore, when you slice with one index, it will return the leftmost value. In the case of A[1], it is row that is indexed.

If it had three dimensions, it would be "pages" that is indexed.


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [83]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [84]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [85]:
for element in A.flat: #This iterates over each element in the 2D-array.
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

"a" is referencing a created array with digits ranging from 0-29.
"b" is referencing a reshaped array of "a" with three axes, turns it from a 1D array to a 3D array with the same numbers.
Where as "a" only had it's numbers aligned on a line, "b" has the same numbers in rows, columns and depth(splitting it into two matrices of columns and rows.)

In [86]:
a = np.arange(30) #a is an array with integers from 0 through to 29.
b = a.reshape((2, 3, -1)) #b is referencing a reshaped 'a', from a 1D array to a 3D array with dimensions 2x3x5.
#Why 5? Because -1 is telling the interpreter that I want it to fill out the last argument so the shape works.
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [87]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [88]:
v1 = np.array([1, 2, 3])
print(v1 + 1)


[2 3 4]


In [89]:
A = np.arange(1, 5).reshape(2,2)
print(A)
b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


In [90]:
print(A + b, '\n"A + b" works because of broadcasting in Numpy, \nbut is not allowed if following mathematical rules because the arrays have not the same size.')
print(np.size(A), '<- size of array A. Size of array b ->', np.size(b))
print()
print(A@b, 'A@b works because of how matrix multiplication is defined. A has the same amount of\ncolumns as b has rows. In linear algebra, this is defined.')

[[3 4]
 [5 6]] 
"A + b" works because of broadcasting in Numpy, 
but is not allowed if following mathematical rules because the arrays have not the same size.
4 <- size of array A. Size of array b -> 2

[ 6 14] A@b works because of how matrix multiplication is defined. A has the same amount of
columns as b has rows. In linear algebra, this is defined.


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [91]:
def add_mult_matrices(m_1, m_2, add_or_mult):
    if not isinstance(m_1, np.ndarray) or not isinstance(m_2,np.ndarray):
        return ValueError, 'Both inputs need to be of type np.ndarray.'
    
    if add_or_mult == 'add':
            if m_1.shape == m_2.shape:
                return m_1 + m_2
            else:
                return ValueError, 'Not defined.'                   
    elif add_or_mult == 'multiply':
            if m_1.shape[1] == m_2.shape[0]:
                return m_1 @ m_2
            else:
                return ValueError, 'Matrice multiplication not defined.'
    else:
        return ValueError, "Third input needs to be 'add' or 'multiply'. Everything else returns error."
        
 

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [92]:
print('10.1.1')
vektor_1 = np.array([4,3])
v1 = vektor_1.reshape((1,2))

print(v1, "The shape of our array.")
print('\n(a)', np.shape(v1))
print('\n(b)', 5*v1)
print('\n(c)', 3*v1)
print('\n(d)', add_mult_matrices((5*v1),(3*v1),'add'))
print('\n(e)', 8*v1)
print('\n(f)', add_mult_matrices((4*v1), -v1, 'add'))
print('\n(g)', np.shape(np.transpose(v1)))
print('\n(h)', add_mult_matrices(v1, np.transpose(v1), 'add'))
print('\n(i)', np.linalg.norm(v1))

10.1.1
[[4 3]] The shape of our array.

(a) (1, 2)

(b) [[20 15]]

(c) [[12  9]]

(d) [[32 24]]

(e) [[32 24]]

(f) [[12  9]]

(g) (2, 1)

(h) (<class 'ValueError'>, 'Not defined.')

(i) 5.0


In [93]:
print('10.1.2')
vektor_2 = np.array([3, 7, 0, 11])
v2 = vektor_2.reshape((4,1))

print(v2, "The shape of our array.")
print('\n(a)', np.shape(v2))
print('\n(b)', 2*v2)
print('\n(c)', add_mult_matrices((5*v2), (2*v2), 'add'))
print('\n(d)', add_mult_matrices((4*v2),  -(2*v2), 'add'))
print('\n(e)', np.shape(np.transpose(v2)))
print('\n(f)', np.linalg.norm(v2))

10.1.2
[[ 3]
 [ 7]
 [ 0]
 [11]] The shape of our array.

(a) (4, 1)

(b) [[ 6]
 [14]
 [ 0]
 [22]]

(c) [[21]
 [49]
 [ 0]
 [77]]

(d) [[ 6]
 [14]
 [ 0]
 [22]]

(e) (1, 4)

(f) 13.379088160259652


In [94]:
print('10.1.3')
ve_1 = np.array([4,3,1,5])
ve1 = ve_1.reshape((1,4))
ve_2 = np.array([2,3,1,1])
ve2 = ve_2.reshape((1,4))

print(ve1, "The shape of our first array.")
print(ve2, "The shape of our second array.")
print('\n(a)', np.linalg.norm(ve1))
print('\n(b)', np.linalg.norm(add_mult_matrices(ve1, -ve2, 'add')))

10.1.3
[[4 3 1 5]] The shape of our first array.
[[2 3 1 1]] The shape of our second array.

(a) 7.14142842854285

(b) 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [95]:
print('10.2.1')
matrix_A = np.array([2,1,-1,1,-1,1])
matrix_B = np.array([4,-2,1,2,-4,-2])
matrix_C = np.array([1,2,2,1])
matrix_D = np.array([3,4,4,3])
matrix_E = np.array([1,2])
matrix_I = np.array([1,0,0,1])
mA = matrix_A.reshape((2,3))
mB = matrix_B.reshape((2,3))
mC = matrix_C.reshape((2,2))
mD = matrix_D.reshape((2,2))
mE = matrix_E.reshape((1,2))
mI = matrix_I.reshape((2,2))

print('\n(A)\n', np.dot(2,mA))
print('\n(B)\n', add_mult_matrices((mB), -(2*mA), 'add'))
print('\n(C)\n', add_mult_matrices((3*mC), -(2*mE), 'add'))
print('\n(D)\n', add_mult_matrices((2*mD), -(3*mC), 'add'))
print('\n(E)\n', add_mult_matrices((np.transpose(mD)), (2*mD), 'add'))
print('\n(F)\n', add_mult_matrices((2*(np.transpose(mC))), -(2*(np.transpose(mD))), 'add'))
print('\n(G)\n', add_mult_matrices((np.transpose(mA)), -mB, 'add'))


10.2.1

(A)
 [[ 4  2 -2]
 [ 2 -2  2]]

(B)
 [[ 0 -4  3]
 [ 0 -2 -4]]

(C)
 (<class 'ValueError'>, 'Not defined.')

(D)
 [[3 2]
 [2 3]]

(E)
 [[ 9 12]
 [12  9]]

(F)
 [[-4 -4]
 [-4 -4]]

(G)
 (<class 'ValueError'>, 'Not defined.')


In [96]:
print('10.2.1')
print('\n(H)\n', add_mult_matrices(mA, mC, 'multiply'))
print('\n(I)\n', add_mult_matrices(mC, mD, 'multiply'))
print('\n(J)\n', add_mult_matrices(mC, mB, 'multiply'))
print('\n(K)\n', add_mult_matrices(mC, mI, 'multiply'))
print('\n(L)\n', add_mult_matrices(mA, (np.transpose(mB)), 'multiply'))

10.2.1

(H)
 (<class 'ValueError'>, 'Matrice multiplication not defined.')

(I)
 [[11 10]
 [10 11]]

(J)
 [[  8 -10  -3]
 [ 10  -8   0]]

(K)
 [[1 2]
 [2 1]]

(L)
 [[5 2]
 [7 4]]


In [97]:
print('10.2.2')
Aarray = np.array([2,3,4,5,4,1])
AA = Aarray.reshape((2,3)) #Döper A från boken till AA här i koden.
print('Calculate A*A^T\n', add_mult_matrices(AA,(np.transpose(AA)), 'multiply'))

10.2.2
Calculate A*A^T
 [[29 26]
 [26 42]]


In [98]:
print('10.2.3\n')
ver_A = np.array([1,2,2,4])
ver_B = np.array([2,1,1,3])
ver_C = np.array([4,3,0,2])
ver_a = ver_A.reshape(2,2)
ver_b = ver_B.reshape(2,2)
ver_c = ver_C.reshape(2,2)
print('\nAB =\n', add_mult_matrices(ver_a, ver_b, 'multiply'))
print('\nAC =\n', add_mult_matrices(ver_a,ver_c, 'multiply'))
print('\nB=\n', ver_b)
print('\nC=\n', ver_c)
print('\nAs can be observed above, "AB = AC", but "B != C".')

10.2.3


AB =
 [[ 4  7]
 [ 8 14]]

AC =
 [[ 4  7]
 [ 8 14]]

B=
 [[2 1]
 [1 3]]

C=
 [[4 3]
 [0 2]]

As can be observed above, "AB = AC", but "B != C".


In [99]:
print('10.2.4\n')
lin_a = np.array([3,2,4,2,3,8,4,1,3,7,1,5])
lin_x = np.array([1,2,3])
lin_b = np.array([7,4,11,9])
LIN_a = lin_a.reshape(4,3)
LIN_x = lin_x.reshape(3,1)
LIN_b = lin_b.reshape(4,1)
print('Ax = B. Har substituerat x1, x2, x3, med siffrorna för jag vet inte hur man gör med variabel.')
print(LIN_a, '\n*\n', LIN_x, '\n=\n', LIN_b)

10.2.4

Ax = B. Har substituerat x1, x2, x3, med siffrorna för jag vet inte hur man gör med variabel.
[[3 2 4]
 [2 3 8]
 [4 1 3]
 [7 1 5]] 
*
 [[1]
 [2]
 [3]] 
=
 [[ 7]
 [ 4]
 [11]
 [ 9]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [100]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)
v3 = v2.copy()
print(v3)

[0 1 2 3]
[2 3]
[2 3]


In [101]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)
print(v3.base)

None
[0 1 2 3]
None


In [102]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [103]:
v3[-1] = 232323

In [104]:
print(v1, '\n', v2, '\n', v3)

[  0   1   2 123] 
 [  2 123] 
 [     2 232323]


# Summary of under "Copies and Views" above:

As seen in examples above. A view of v1[-2:] is simply referencing to v1 but starting from last 2 indexes to the end. Any changes

on v2 are on v1 because they are using the same data, just that v2 is showing parts of it.

v3 on the other hand, makes a copy of v2 and changes made to this copy will remain with this copy and not affect v2, because it is now

it's own set of data.